config/routes.rb
ClientMail::Application.routes.draw do
  
  resources :contacts
  post 'contact/compose_mail'
  get 'contact/compose_mail'
  post 'contact/create' => 'contact#create'

  #-------------------Routes For Receivemail-----------------------#
  post 'sentmails/compose_mail'
  get 'sentmails/compose_mail'
  get 'sentmails/star'=>'sentmails#star'
  post 'sentmails/star'=>'sentmails#star'

  get 'sentmails/show' => 'sentmails#show'
  post 'sentmails/show' => 'sentmails#show'

  get 'sentmails/drafts'=>'sentmails#drafts'
  post 'sentmails/drafts'=>'sentmails#drafts'

  get 'sentmails/starred'=>'sentmails#starred'
  post 'sentmails/starred'=>'sentmails#starred'

  get 'sentmails/autocomplete'=>'sentmails#autocomplete'
  post 'sentmails/autocomplete'=>'sentmails#autocomplete'

  post 'sentmails/destroy_mail' => 'sentmails#destroy_mail'
  get 'sentmails/destroy_mail' => 'sentmails#destroy_mail'

  get 'sentmails/compose' => 'sentmails#compose_mail'
  get 'sentmails/sended' => 'sentmails#sended'
  post 'sentmails/create' => 'sentmails#create'
  #--------------------------------Routs for Receive mail---------------------------------#
  get 'receivemail/inbox' => 'receivemail#inbox'
  post 'receivemail/inbox' => 'receivemail#inbox'
  
  get 'receivemail/read'=>'receivemail#read'
  post 'receivemail/read'=>'receivemail#read'

  get 'receivemail/star'=>'receivemail#star'
  post 'receivemail/star'=>'receivemail#star'

  get 'receivemail/trash_mail'

  get 'receivemail/all_mail'
  post 'receivemail/all_mail'

  
  get 'receivemail/show' => 'receivemail#show'

  get 'receivemail/delete'=>'receivemail#delete'
  post 'receivemail/delete'=>'receivemail#delete'
 
  get 'receivemail/trash_mail' => 'receivemail#trash_mail'	
  post'receivemail/trash_mail' => 'receivemail#trash_mail'  
 
 #get '/:id' => "shortener/shortened_urls#show"
  
  #root 'receivemail#inbox'
  root :to => 'receivemail#inbox'
  
end

app/models/receivemail.rb
class Receivemail < ActiveRecord::Base
end

app/controllers/receivemail_controller.rb
class ReceivemailController < ApplicationController
  
  def inbox
  	  @receive_mails = Receivemail.where(delete_check: nil).where('last_uid > ? ',0).order(date: :desc)
 
 end

def read
  @receivemails_read_check=Receivemail.find(params[:pt])
    if@receivemails_read_check.read_unread_check == true
      @receivemails_read_check.read_unread_check = false
      @receivemails_read_check.save
    end
    redirect_to :back
end


 def star
  
   @receive_mails = Receivemail.all
   
    @receive_mails = Receivemail.find(params[:id])
       if @receive_mails.star_check == nil
           @receive_mails.star_check = 2
       else
          @receive_mails.star_check = nil
       end
   @receive_mails.save
   if @receive_mails.save
    redirect_to :back
    end

end

  def show
  	
      @receive_mails =Receivemail.find(params[:id])
      # z =  @instance.parse_mail(@receive_mails.parsedbody)
      #@decoded = z
      gon.from_mail = @receive_mails.from_mail
      
      gon.html_text = @receive_mails.parsed_html_body

  
  end

  def all_mail
     @receive_mails = Receivemail.where('last_uid >?',0)

  end

def delete
  puts "hi......"
        @receivemail_delete_id_string=params[:pt]
        @receivemail_delete_id_array=[]

        @receivemail_delete_id_string.split(",").each do |i|
        if i !=','    
           
        @receivemail_delete_id_array << i

        end
      end
     @receivemail_delete_id_array.each do|id|
     @receivemails = Receivemail.find(id)
     @receivemails.delete_check = 1
     @receivemails.save
     end
    redirect_to receivemail_inbox_url
  end

def create
end


def trash_mail
      @receive_mails = Receivemail.where(delete_check: 1).where('last_uid > ? ',0)

end

end



# class DecodeMail
  
#   require 'base64'
#   require 'enumerator'
 
#   def decode(x)
#     y = Base64.decode64('-6aWQ9YnFibXRwLG1taWQ9MWNpLWJxYm10cC0yemlxOWo5ZS1jNTIsYXBwaWQ9Mix0PTUyNyxzPTEsdj0yMyx1PTM0NDUzNDM1LGY9LGQ9MTQ3MzQwMjYwNCxtPXA=')
#     d = y.force_encoding('UTF-8','UTF-16')
#     puts y
#   return y
#   end

#   def parse_mail(st)
    
#     if st.include? "="
      
      
#       return new_st
#     else
     
#       positions = st.enum_for(:scan, /</).map { Regexp.last_match.begin(0) }
#       last_positions = st.enum_for(:scan, /--001/).map { Regexp.last_match.begin(0) }
#       actual_pos = positions.first.to_i
#       last_pos = last_positions.first.to_i-35
#       new_st = st[actual_pos..last_pos]
#       puts new_st
#       return new_st
#     end
    
    
#   end
# end

app/helpers/receivemail_helper.rb
module ReceivemailHelper
end

app/views/receivemail/_reply.html.erb
<%= tinymce_assets %>
<%= tinymce %>

<%= form_tag({:controller => :sentmails, :action => :create}, :multipart => true) do %>
        
       
        <div class="form-group">
          <div class="col-xs-1"> <%= label_tag :"To:" %></div>
          <div class="col-sm-9"><%= text_field_tag :to, "", class:'form-control', placeholder: "Recipients" %>
          <div>
           <a href="javascript:void(0)" id="cc">cc</a>
           <a href="javascript:void(0)" id="bcc">Bcc</a>
          </div>
         </div>
        </div>
       <br>
       <br>
       
       <div class="form-group" id="cc_div_id" style="display: none">
         <div class="col-xs-1"> <%= label_tag :"CC: "%> </div>
         <div class="col-sm-9">  <%= text_field_tag :cc,"",class:'form-control', placeholder: "Recipients" %></div>
       </div>

       <br>
          <div class="form-group" id="bcc_div" style="display: none">
             <div class="col-xs-1"> <%= label_tag :"Bcc:" %></div>
             <div class="col-sm-9"><%= text_field_tag :bcc, "", class:'form-control', placeholder: "Recipients" %></div>
          </div>
       <br>

        <div class="form-group">
          <div class="col-xs-1">  <%= label_tag :"Subject:" %></div>
           <div class="col-sm-9"><%= text_field_tag :sub, "", class:'form-control', placeholder: "Subject" %></div>
        </div>
       <br>
       
         <div class="form-group">
           <div class="col-xs-1">  <%= label_tag :"  " %></div>
            <div class="col-sm-9"><%= text_area_tag :body, "", cols:300,rows:9,class:'tinymce form-control' %></div>
         </div>
        <br>
           <div class="form-group">
              <div class="col-xs-3"> <%= label_tag :"Attachment:" %></div>
              <div class="col-sm-9"> <%= file_field_tag :image  %></div>
             <!--  <%= file_field_tag 'picture' %> -->
           </div>
      <br>
    
          <div class="form-group">
              <div class="col-xs-3"><%= submit_tag :Send, :class =>"btn btn-primary" %></div>
           </div>

           <div class="form-group">
              <div class="col-xs-2"><%= button_tag :Cancel, :class =>"btn btn-primary" %></div>
           </div>
        <% end %>




<script type="text/javascript">

tinyMCE.init({
    selector: 'textarea.editor'
  });
 
 $("#cc").click(function(){
   $("#cc_div_id").show();
 
  //$("#cc_div_id").append();
   
   $("#cc").hide();
  });

$("#bcc").click(function(){
   $("#bcc_div").show();
   $("#bcc").hide();
  });


</script>

app/views/receivemail/all_mail.html.erb
<div id="all_mail_search-area" class="all_mail_search-area container" ></div>
<div class="container" style="position:relative;left:110px;top:-370px;background-color:#ECF0F1; ">
<table id="AllMailTable" class="display nowrap" cellspacing="0" style="cursor:pointer;table-layout: fixed;">
  <thead>
    <tr>
     
      <th>From</th>
      <th>Mail</th>
      <th>Date</th>
     </tr>
  </thead>

  <tbody>
    <% @receive_mails.each do |receive_mail| %>
    
       <tr data-link="<%= receivemail_show_path("id" => receive_mail.id) %>" >

          <td><%= receive_mail.from%></td>
          <td style="overflow:hidden;"><strong><%= receive_mail.sub %></strong>&nbsp;&nbsp;&nbsp;<%= receive_mail.parsed_plain_body %></td>

          <td><%= receive_mail.date.strftime("%e %b, %Y")%></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>


<style type="text/css">
  .all_mail_search-area {
   width: 100%;
    clear: both;
    padding-top: 20px;
    padding-bottom: 20px;
    position:relative;
    left:200px;
    top:-450px;  
}

.all_mail_search-area input{
  width: 600px;
    font-size: 20px;
    padding: 5px;  
}
</style>

<script type="text/javascript">
  $(document).ready(function() {
      $('#AllMailTable').dataTable( {
          initComplete : function() {
           $("#AllMailTable_filter").detach().appendTo('#all_mail_search-area');
             },  
           "columnDefs": [
                          { "width": "60px", "targets": 0 },
                          { "width": "550px", "targets": 1 },
                          { "width": "30px", "targets": 2 }
                         ],          
      } );
  } );
           jQuery(function($) {
          $("tr[data-link]").click(function() {
          window.location = $(this).data('link');
         // window.location = this.dataset.link
      });

  });
</script>

app/views/receivemail/delete.html.erb
<h1>Receivemail#delete</h1>
<p>Find me in app/views/receivemail/delete.html.erb</p>

app/views/receivemail/inbox.html.erb
<div id="receivemail_search-area" class ="receivemail_search-area container"></div>

<div class="container" style="position:relative;left:110px;top:-400px;background-color:#ECF0F1; ">
<p align="center" id="notice"><%= notice %></p>
<table id="receivemailTable" class="display nowrap" cellspacing="0" style="cursor:pointer;table-layout: fixed;">
  <thead>
    <tr>
      <th><div><button class="delete_receivemail">
      <i class="glyphicon glyphicon-trash"></i></button></div></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @receive_mails.each do |receive_mail| %>
        <% if receive_mail.read_unread_check == true %>
           <tr  id= "<%= receive_mail.id%>", class="selected" >
            
               <td id ="delete_receive"><%= check_box_tag 'receive_mail[]' , receive_mail.id,false, class: 'receive_delete' %></td> 
<!-- Link Starred -->
           <td> 
              <% if receive_mail.star_check==2 %>
                 <%=link_to receivemail_star_path("id" => receive_mail.id), data: {  }, class: "btn btn-default btn-xs" do%>
                  <i class="glyphicon glyphicon-star"></i>  
              <%end%>

              <%else%>
                  <%=link_to receivemail_star_path("id" => receive_mail.id), data: {  }, class: "btn btn-default btn-xs" do%>
                  <i class="glyphicon glyphicon-star-empty"></i>
              <%end%>
          <%end%>
                </td> 
<!--  -->
               <td data-link="<%= receivemail_show_path("id" => receive_mail.id) %>"><%= receive_mail.from%></td>

               <td style="overflow:hidden;" data-link="<%= receivemail_show_path("id" => receive_mail.id) %>"><strong><%= receive_mail.sub %></strong>&nbsp;&nbsp;&nbsp;<%= receive_mail.parsed_plain_body %></td>
            
              <td data-link="<%= receivemail_show_path("id" => receive_mail.id) %>"><%= receive_mail.date.strftime("%e %b, %Y")%></td>
          </tr>
          <%else%>
<!--  -->
          <tr id="<%= receive_mail.id%>" >
              
                <td id ="delete"><%= check_box_tag 'receive_mail[]' , receive_mail.id,false, class: 'receive_delete' %></td> 
               <td> 

            <% if receive_mail.star_check==2 %>
                 <%=link_to receivemail_star_path("id" => receive_mail.id), data: {  }, class: "btn btn-default btn-xs" do%>
                  <i class="glyphicon glyphicon-star"></i>  
              <%end%>
              <%else%>
                  <%=link_to receivemail_star_path("id" => receive_mail.id), data: {  }, class: "btn btn-default btn-xs" do%>
                  <i class="glyphicon glyphicon-star-empty"></i>
              <%end%>
             <%end%>
                </td> 
              

               <td data-link="<%= receivemail_show_path("id" => receive_mail.id) %>"><%= receive_mail.from%></td>
               <td data-link="<%= receivemail_show_path("id" => receive_mail.id) %>" style="overflow:hidden;"><strong><%= receive_mail.sub %>
               </strong>&nbsp;&nbsp;&nbsp;<%= receive_mail.parsed_plain_body %></td>
               <td data-link="<%= receivemail_show_path("id" => receive_mail.id) %>"><%= receive_mail.date.strftime("%e %b, %Y")%></td>
          </tr>
        <% end %>
    <% end %>
  </tbody>
</table>
</div>
<br>

<style>

.glyphicon-star {
    color: #FFF000;
}
</style>


<script type="text/javascript">
// ------------------------dataTable------------------------------------//
$(document).ready(function() {
    $('#receivemailTable').dataTable( {
        initComplete : function() {
          $("#receivemailTable_filter").detach().appendTo('#receivemail_search-area');
           },  
         "columnDefs": 
         [
      { "width": "5px", "targets": 0 },
      { "width": "10px", "targets": 1 },
      { "width": "50px", "targets": 2 },
      { "width": "500px", "targets":3 },
      { "width": "50px", "targets": 4}
       ],
      "bSort" : false
    } );
} );

// ------------------------------Read/Unread---------------------------//
$(document).ready(function() {

       $('#receivemailTable tbody').on( 'click', 'tr', function () {

          var desired_id = $(this).prop('id');
        
          $.getScript('/receivemail/read.js?pt='+ desired_id);        
     } );
        
} );

//-------------------------Multi Delete----------------------------------//

$(".delete_receivemail").hide();
$(".receive_delete").click(function() {

  var captured_id=$(this).prop('value');    
//alert(captured_id);
      
    if($('.receive_delete').is(":checked")) {
        $(".delete_receivemail").show();

    } else {
        $(".delete_receivemail").hide();
    }
});


$(".delete_receivemail").click(function() {

var id_list = [];
//alert(id_list);
$.each($("input[name='receive_mail[]']:checked"), function(){            
  id_list.push($(this).val());
});
alert(id_list);

var x=confirm("Are you sure you want to delete?");
if (x)
       $.getScript('/receivemail/delete.js?pt='+ id_list);
     
  else
return false;
location.reload();
});

//-----------------------------------//
jQuery(function($) {
    $("td[data-link]").click(function() {

        window.location = $(this).data('link');    
    });
}); 

</script>

app/views/receivemail/show.html.erb
<div style="position:relative;left:250px;top:-250px;width:1000px;`">
<p>
  <strong><%= @receive_mails.sub %></strong>
</p>
<hr>
<p>
  <strong>from:</strong>
  <%= @receive_mails.from %>
</p>

<p>
  <strong>date:</strong>
  <%= @receive_mails.date %>
</p>
<hr>
<p>
 <div id="body_html"> 
   <%= raw @receive_mails.parsed_html_body %>
  </div>
</p>

<hr>
  <div id="receivemail_reply" style="background-color:#ECF0F1; position:absolute; width:1000px;">
     <p>
      click here to 
       <a href="javascript:void(0)" id="receive_reply_link">Reply</a>or
       <a href="javascript:void(0)" id="receive_forward_link">Forward</a>
     </p>
  </div>
<hr>
<script >
$("#receive_reply_link").click(function(){
  alert(gon.from_mail);
$("#receivemail_reply").html("<%= escape_javascript(render 'reply') %>");
$("#to").val(gon.from_mail);
});

$("#receive_forward_link").click(function(){
//alert("hi....")
$("#receivemail_reply").html("<%= escape_javascript(render 'reply') %>");
$("#body").val(gon.html_text);
});
</script>

app/views/receivemail/trash_mail.html.erb
<p id="notice"><%= notice %></p>
<div id="trash_mail_search-area" class="container"></div>
<div class="container" style="position:relative;left:110px;top:-370px;background-color:#ECF0F1; ">
<table id="trash_Mail_Table" class="display nowrap" cellspacing="0" style="cursor:pointer;table-layout: fixed;">
  <thead>
    <tr>
      <th>From</th>
      <th>Mail</th>
      <th>Date</th>
    </tr>
  </thead>

  <tbody>
     <% @receive_mails.each do |receive_mail| %>
    
       <tr data-link="<%= receivemail_show_path("id" => receive_mail.id) %>" >

          <td><%= receive_mail.from%></td>
          <td style="overflow:hidden;">
             <strong><%= receive_mail.sub %></strong>&nbsp;&nbsp;&nbsp;<%= receive_mail.parsed_plain_body %>
          </td>
          <td><%= receive_mail.date.strftime("%e %b, %Y")%></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>


<script type="text/javascript">
$(document).ready(function() {
    $('#trash_Mail_Table').dataTable( {
        initComplete : function() {
         $("#trash_Mail_Table_filter").detach().appendTo('#trash_mail_search-area');
           },  
         "columnDefs": [
                        { "width": "60px", "targets": 0 },
                        { "width": "550px", "targets": 1 },
                        { "width": "30px", "targets": 2 }
                       
                ]
         } );
} );
         jQuery(function($) {
        $("tr[data-link]").click(function() {
        window.location = $(this).data('link');
       // window.location = this.dataset.link
    });

});
</script>