config/routes.rb
ClientMail::Application.routes.draw do
  
  resources :contacts
  post 'contact/compose_mail'
  get 'contact/compose_mail'
  post 'contact/create' => 'contact#create'

  #-------------------Routes For Receivemail-----------------------#
  post 'sentmails/compose_mail'
  get 'sentmails/compose_mail'
  get 'sentmails/star'=>'sentmails#star'
  post 'sentmails/star'=>'sentmails#star'

  get 'sentmails/show' => 'sentmails#show'
  post 'sentmails/show' => 'sentmails#show'

  get 'sentmails/drafts'=>'sentmails#drafts'
  post 'sentmails/drafts'=>'sentmails#drafts'

  get 'sentmails/starred'=>'sentmails#starred'
  post 'sentmails/starred'=>'sentmails#starred'

  get 'sentmails/autocomplete'=>'sentmails#autocomplete'
  post 'sentmails/autocomplete'=>'sentmails#autocomplete'

  post 'sentmails/destroy_mail' => 'sentmails#destroy_mail'
  get 'sentmails/destroy_mail' => 'sentmails#destroy_mail'

  get 'sentmails/compose' => 'sentmails#compose_mail'
  get 'sentmails/sended' => 'sentmails#sended'
  post 'sentmails/create' => 'sentmails#create'
  #--------------------------------Routs for Receive mail---------------------------------#
  get 'receivemail/inbox' => 'receivemail#inbox'
  post 'receivemail/inbox' => 'receivemail#inbox'
  
  get 'receivemail/read'=>'receivemail#read'
  post 'receivemail/read'=>'receivemail#read'

  get 'receivemail/star'=>'receivemail#star'
  post 'receivemail/star'=>'receivemail#star'

  get 'receivemail/trash_mail'

  get 'receivemail/all_mail'
  post 'receivemail/all_mail'

  
  get 'receivemail/show' => 'receivemail#show'

  get 'receivemail/delete'=>'receivemail#delete'
  post 'receivemail/delete'=>'receivemail#delete'
 
  get 'receivemail/trash_mail' => 'receivemail#trash_mail'	
  post'receivemail/trash_mail' => 'receivemail#trash_mail'  
 
 #get '/:id' => "shortener/shortened_urls#show"
  
  #root 'receivemail#inbox'
  root :to => 'receivemail#inbox'
  
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @all_contacts = Contact.all
 
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    
    @contact =Contact.new(contact_params)
    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
     # params.fetch(:contact, {})
       params.require(:contact).permit(:name,:mail_id,:contact_no,:dob,:gender,:location)
        #params.require(:contact).permit!
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
   
  <% end %>

<div>
    <%= f.label :Name %><br>
    <%= f.text_field :name %>
</div>
<div>
   <%= f.label :Mail %><br>
    <%= f.text_field :mail_id %>
    </div>
<div>
    <%= f.label :Contactno %><br>
    <%= f.text_field :contact_no %>
</div>
<div>
    <%= f.label :DOB %><br>
    <%= f.text_field :dob %>
</div>
<div>
    <%= f.label :Gender %><br>
    <%= f.text_field :gender%>
</div>
<div>
    <%= f.label :Location %><br>
    <%= f.text_field :location %> 
    </div>
<div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<div class="container" style="position:relative;left:110px;top:-370px;background-color:#ECF0F1; ">
<h1>Editing Contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>
</div>

app/views/contacts/index.html.erb
<div class="container" style="position:relative;left:110px;top:-300px;background-color:#ECF0F1; ">
<p id="notice"><%= notice %></p>

<h3>Listing Mail</h3>

<table id="contact_List_Table">
  <thead>
    <tr>
    <th>Name</th>
    <th>Mail</th>
    <th>contact No.</th>
    <th>Date Of Birth</th>
    <th>Gender</th>
    <th>Location</th>
    <th ></th>
    <th></th>
    
    </tr>
  </thead>

  <tbody>
    <% @all_contacts.each do |contact| %>
      <tr>
      <td><%= contact.name %></td>
      <td><%= contact.mail_id %></td>
      <td><%= contact.contact_no %></td>
      <td><%= contact.dob %></td>
      <td><%= contact.gender %></td>
      <td><%= contact.location %></td>
      <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
      <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button><%= link_to 'New Contact', new_contact_path %></button>
</div>



<script type="text/javascript">
  $(document).ready(function() {
    $('#contact_List_Table').dataTable( {
        
} );
  });
</script>

app/views/contacts/new.html.erb
<div class="container" style="position:relative;left:110px;top:-320px;background-color:#ECF0F1; ">
<h1>New Contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>
</div>

app/views/contacts/show.html.erb
<div class="container" style="position:relative;left:110px;top:-370px;background-color:#ECF0F1; ">
<p id="notice"><%= notice %></p>
<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>
<p>
  <strong>Mail Id:</strong>
  <%= @contact.mail_id %>
</p>
<p>
  <strong>Contact Number:</strong>
  <%= @contact.contact_no %>
</p>
<p>
  <strong>Gender:</strong>
  <%= @contact.gender %>
</p>
<p>
  <strong>Location:</strong>
  <%= @contact.location%>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>
</div>