config/routes.rb
ClientMail::Application.routes.draw do
  
  resources :contacts
  post 'contact/compose_mail'
  get 'contact/compose_mail'
  post 'contact/create' => 'contact#create'

  #-------------------Routes For Receivemail-----------------------#
  post 'sentmails/compose_mail'
  get 'sentmails/compose_mail'
  get 'sentmails/star'=>'sentmails#star'
  post 'sentmails/star'=>'sentmails#star'

  get 'sentmails/show' => 'sentmails#show'
  post 'sentmails/show' => 'sentmails#show'

  get 'sentmails/drafts'=>'sentmails#drafts'
  post 'sentmails/drafts'=>'sentmails#drafts'

  get 'sentmails/starred'=>'sentmails#starred'
  post 'sentmails/starred'=>'sentmails#starred'

  get 'sentmails/autocomplete'=>'sentmails#autocomplete'
  post 'sentmails/autocomplete'=>'sentmails#autocomplete'

  post 'sentmails/destroy_mail' => 'sentmails#destroy_mail'
  get 'sentmails/destroy_mail' => 'sentmails#destroy_mail'

  get 'sentmails/compose' => 'sentmails#compose_mail'
  get 'sentmails/sended' => 'sentmails#sended'
  post 'sentmails/create' => 'sentmails#create'
  #--------------------------------Routs for Receive mail---------------------------------#
  get 'receivemail/inbox' => 'receivemail#inbox'
  post 'receivemail/inbox' => 'receivemail#inbox'
  
  get 'receivemail/read'=>'receivemail#read'
  post 'receivemail/read'=>'receivemail#read'

  get 'receivemail/star'=>'receivemail#star'
  post 'receivemail/star'=>'receivemail#star'

  get 'receivemail/trash_mail'

  get 'receivemail/all_mail'
  post 'receivemail/all_mail'

  
  get 'receivemail/show' => 'receivemail#show'

  get 'receivemail/delete'=>'receivemail#delete'
  post 'receivemail/delete'=>'receivemail#delete'
 
  get 'receivemail/trash_mail' => 'receivemail#trash_mail'	
  post'receivemail/trash_mail' => 'receivemail#trash_mail'  
 
 #get '/:id' => "shortener/shortened_urls#show"
  
  #root 'receivemail#inbox'
  root :to => 'receivemail#inbox'
  
end

app/models/sentmail.rb
class Sentmail < ActiveRecord::Base
	
end

app/controllers/sentmails_controller.rb
class SentmailsController < ApplicationController
  require 'nokogiri'
  require 'time'
  require 'active_support'

  def compose_mail
  
  	 @sentmail = Sentmail.new
   
  end
#--------------------------------------------Auto Complete---------------------------------------#
  def autocomplete
    @check=params[:pt]

    if @check==nil
      @check=" "
      unique_val=100
    else
      ret_sen_array=string_array_conversion(@check)
      compact_word_array=Array.new
      ret_sen_array.each do |word|
      compact_word=check_ultimate(word)
      compact_word_array.push(compact_word)
    end
      dynamic_query(compact_word_array)
    end
  end


 def check_ultimate(get_val)
    remove_data=get_val.to_s.chomp
    final_st_two=remove_data.gsub(/[^a-zA-Z0-9\-]/,"").downcase
    return final_st_two
end

  def dynamic_query(source_array)
 # @query_string=""
 @firstname_array=Array.new
 @ko=Contact.where('compact_string LIKE ?', '%' +  source_array[0] + '%')
 source_array=source_array-[source_array[0]]

 source_array.each do |w|
    @ko=@ko.where('compact_string LIKE ?', '%' + w + '%')
 end
  @ko.each do |k|
    @firstname_array && @firstname_array.push(k.mail_id)
  end
    puts "----------------------------------------"
    puts @firstname_array.length
    puts @firstname_array
    gon.mailid = @firstname_array
    puts "----------------------------------------"

    respond_to do |format|
      format.html
      format.js { render action: 'atcomp' }
    end
 
end


 def string_array_conversion(sentence)
  return unless sentence
  sen_array=Array.new

  values = sentence.split(" ")
 
   values.each do |value|
     sen_array.push(value)
      puts"*******************************"
      puts value
   end
    # puts "this is the array"
    # puts sen_array
    return sen_array
  
 end
#-------------------------------------------------End Of AutoComplete----------------------------#

def create
     
     @sentmails = Sentmail.new
     @new_contacts = Contact.new
     #@sendmails.from=params[:from]
     @sentmails.to=params[:to]
     @new_contacts.mail_id=params[:to]
     @sentmails.cc=params[:cc]
     @sentmails.bcc=params[:bcc]
     @sentmails.sub=params[:sub]
     @sentmails.body=params[:body]
     @sentmails.body_text = Nokogiri::HTML(params[:body]).text
     @sentmails.save
    if Contact.exists? mail_id: @new_contacts.mail_id
     puts "mail id already already exist....................!"
   else
    @new_contacts.save
    
   end 

if @sentmails.save
   #    t = Thread.new do
       UserMailer.sending_mail(@sentmails).deliver_now
       
  	 	flash[:info]='Message sended Successfully'
       gon.to = @sentmails.to
   #    at_exit{ t.join }
   #    end
    else
    	puts"error in saving mail"
    end
     respond_to do |format|
      format.html { redirect_to root_url, notice: 'Your message has been sent. ' }
      format.json { head :no_content }
   end
   # redirect_to 
   end


  def sended
    @sentmails = Sentmail.where(delete_check: nil).order(created_at: :desc)
    
  end 


  def show
  puts "hi.."
   @sentmails = Sentmail.find(params[:id])
   puts @sentmails
  gon.to = @sentmails.to
  puts gon.to
  gon.body_text = @sentmails.body_text
  # render :show
  end

def star
   @sentmails = Sentmail.all
    @sentmails = Sentmail.find(params[:id])
       if @sentmails.star_check == nil
       @sentmails.star_check = 2
       else
    @sentmails.star_check = nil
  end
   @sentmails.save
   if @sentmails.save
   redirect_to :back
    end
end

def starred
  @sentmails = Sentmail.where('star_check =?',2)
  @receivemails = Receivemail.where('star_check =?',2)
  @mails=@sentmails+@receivemails
  @mails=@mails

end

def drafts
  
end

  def destroy_mail
    
      @sentmail_delete_id_string=params[:pt]
        @sentmail_delete_id_array=[]

        @sentmail_delete_id_string.split(",").each do |i|
        if i !=','    
           
        @sentmail_delete_id_array << i

        end
      end
     @sentmail_delete_id_array.each do|id|
     @sentmails = Sentmail.find(id)
     @sentmails.delete_check = 1
     @sentmails.save
     end
     redirect_to sentmail_sended_url
  end
end


private
def sentmails_params
  params.require(:sentmail).permit(:image)
end

app/helpers/sentmail_helper.rb
module SentmailHelper
end

app/views/sentmails/_reply.html.erb
<%= tinymce_assets %>
<%= tinymce %>

<%= form_tag({:action => :create}, :multipart => true) do %>
       <br>
        <div class="form-group">
          <div class="col-xs-1"> <%= label_tag :"To:" %></div>
          <div class="col-sm-9">
         <%= text_field_tag :to , "", class:'form-control', placeholder: "Recipients",id:'contacts_field' %>
          <div>
           <a href="javascript:void(0)" id="cc">cc</a>
           <a href="javascript:void(0)" id="bcc">Bcc</a>
          </div>
         </div>
        </div>
       <br>
          <div class="form-group" id="cc_div_id" style="display: none">
             <div class="col-xs-1"> <%= label_tag :"cc:" %></div>
             <div class="col-sm-9"><%= text_field_tag :cc, "", class:'form-control', placeholder: "Recipients" %></div>
          </div>
       <br>

       
          <div class="form-group" id="bcc_div" style="display: none">
             <div class="col-xs-1"> <%= label_tag :"Bcc:" %></div>
             <div class="col-sm-9"><%= text_field_tag :bcc, "", class:'form-control', placeholder: "Recipients" %></div>
          </div>
       <br>

        <div class="form-group">
          <div class="col-xs-1">  <%= label_tag :"Subject:" %></div>
           <div class="col-sm-9"><%= text_field_tag :sub, "", class:'form-control', placeholder: "Subject" %></div>
        </div>
       <br>
       
         <div class="form-group">
           <div class="col-xs-1">  <%= label_tag :"  " %></div>
            <div class="col-sm-9"><%= text_area_tag :body, "", cols:300,rows:9,class:'tinymce form-control' %></div>
         </div>
        <br>
           <div class="form-group">
              <div class="col-xs-3"> <%= label_tag :"Attachment:" %></div>
              <div class="col-sm-9"> <%= file_field_tag :image  %></div>
             <!--  <%= file_field_tag 'picture' %> -->
           </div>
      <br>
       <br>
          <div class="form-group">
              <div class="col-xs-3"><%= submit_tag :Send, :class =>"btn btn-primary" %></div>
           </div>
            <div class="form-group">
              <div class="col-xs-3"><%= button_tag :Cancel, :class =>"btn btn-primary" %></div>
           </div>
        <% end %>




<script type="text/javascript">



tinyMCE.init({
    selector: 'textarea.editor'
  });
 
 $("#cc").click(function(){
   $("#cc_div_id").show();
 
  //$("#cc_div_id").append();
   
   $("#cc").hide();
  });

$("#bcc").click(function(){
   $("#bcc_div").show();
   $("#bcc").hide();
  });


</script>

app/views/sentmails/compose_mail.html.erb
<%= tinymce_assets %>
<%= tinymce %>

<div class="container" style="position:relative;left:110px;top:-320px;background-color:#ECF0F1; width:300; ">
   <h3><center>Send New Mail</center></h3>
   
    <div id="compose_mail_area" >
     <%= form_tag({:action => :create}, :multipart => true) do %>
        
        <% if @sentmail.errors.any? %>
          <div class="error_messages">
            <h2>Form is invalid</h2>
            <ul>
              <% for message in @sentmail.errors.full_messages %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
       <br>
       <br>
        <div class="form-group">
          <div class="col-xs-1"> <%= label_tag :"To:" %></div>
          <div class="col-sm-8 " ><%=  text_field_tag :"to", '',class:'form-control draggable', placeholder: "Recipients" %>
           <span>
         
           <a href="javascript:void(0)" id="cc">cc</a>
           <a href="javascript:void(0)" id="bcc">Bcc</a>
          </span>
         </div>
        </div>
       <br>
       
       
       <div class="form-group" id="cc_div_id" style="display: none">
         <div class="col-xs-1"> <%= label_tag :"CC:" %> </div>
         <div class="col-sm-8" id="droppable">  <%= text_field_tag :cc,"",class:'form-control', placeholder: "Recipients" %></div>
       </div>

       <br>
          <div class="form-group" id="bcc_div" style="display: none">
             <div class="col-xs-1"> <%= label_tag :"Bcc:" %></div>
             <div class="col-sm-8" id="droppable"><%= text_field_tag :bcc, "", class:'form-control', placeholder: "Recipients" %></div>
          </div>
       <br>

        <div class="form-group">
          <div class="col-xs-1">  <%= label_tag :"Subject:" %></div>
           <div class="col-sm-8"><%= text_field_tag :sub, "", class:'form-control', placeholder: "Subject" %></div>
        </div>
       <br>
       
         <div class="form-group">
           <div class="col-xs-1">  <%= label_tag :"  " %></div>
            <div class="col-sm-9"><%= text_area_tag :body, "", cols:300,rows:9,class:'tinymce form-control' %></div>
         </div>
        <br>
        
           <div class="form-group">
              <div class="col-xs-3"> <%= label_tag :"Attachment:" %></div>
              <div class="col-sm-8"> <%= file_field_tag :image  %></div>
             <!--  <%= file_field_tag 'picture' %> -->
           </div>
       <br>
       
          <div class="form-group">
              <div class="col-xs-3"><%= submit_tag :Send, :class =>"btn btn-primary" %></div>
           </div>
        <% end %>
 </div>

</div>
<script type="text/javascript">

tinyMCE.init({
    selector: 'textarea.editor'
  });
 
 $("#cc").click(function(){
   $("#cc_div_id").show();
 
  //$("#cc_div_id").append();
   
   $("#cc").hide();
  });

$("#bcc").click(function(){
   $("#bcc_div").show();
   $("#bcc").hide();
  });

//----------------------------Start Draggable & Dropable---------------// 
$(function() {
    $(".draggable").draggable({
        revert: true,
        helper: 'clone',
        start: function(event, ui) {
            $(this).fadeTo('fast', 0.5);
        },
        stop: function(event, ui) {
            $(this).fadeTo(0, 1);
        }
    });
    
    $("#droppable").droppable({
        hoverClass: 'active',
        drop: function(event, ui) {
            this.value = $(ui.draggable).text();
        }
    });
});

//------------------------ End Of Draggable & Dropable----------------------//



  // $(document).ready(function () {
  //   $("#to").keyup(function () {

  //     var box = document.getElementById("to");
  //     document.getElementById("abc").innerHTML = box.value;
  //     $.getScript('/sentmails/autocomplete.js?pt=' + encodeURIComponent(box.value))
  //   });
  // });

</script>

app/views/sentmails/sended.html.erb
<!-- <script type="text/javascript">

// jQuery(function($) {

//     $("tr[data-link]").click(function() {
//         window.location = $(this).data('link');
//             if ($(this).index() == 5 ) { 
//                return;
//           }
//        // window.location = this.dataset.link
//     });
// }); 
$("#sentmailTable tbody").on('click', 'td', function () {

         //  if ($(this).index() == 5 ) { // provide index of your column in which you prevent row click here is column of 4 index
         //      return;
         // }
         alert("hi......")

            // you can do additional functionality by clicking on this column here                         
    });

$(' tbody').on( 'click', 'td', function () { 
  var idx = table.cell(this).index().column;
  var ColumnHeader = table.column(idx).header();
  var FirstColumnValue = Noclue;
  location.href = "Page.cshtml?ID=" + ColumnHeader + "Name=" + FirstColumnValue;
});


$("#sentmailTable").on("click", "td:nth-child(2)", function(e) {
    $(this).prev().html();  //Get the previous sibling's HTML without inline JS
});

$('#sentmailTable tr').find('td:fifth').on('click', function (e) {
  alert("hi......");
  window.location = $(this).data('link');
   window.location.href = $(this).data('url');
 e.preventDefault();
 e.stopPropagation();
});
</script> -->


<div class="container" id="new-search-area" ></div>

  <div class="container" style="position:relative;left:110px;top:-400px;background-color:#ECF0F1; ">
<div>
<button class="delete_link"> 
    
    <i class="glyphicon glyphicon-trash"></i> </button>
</div>
  
  <table id="sentmailTable" class="display nowrap" cellspacing="0" style="cursor:pointer;table-layout: fixed;">
  <thead> 

    <tr>
      <th><%= check_box_tag id ="selectall"%></th> 
      <th></th>
      <th></th>
      <th></th>
      <th></th>
     </tr>
  </thead>  

  <tbody>
    <% @sentmails.each do |sentmail| %>
      <tr >
        <td id ="delete"><%= check_box_tag 'sentmail[]' , sentmail.id,false, class: 'starry' %></td> 

        <td>
        <% if sentmail.star_check==2 %>
         <i class="active clickable">
           <%=link_to sentmails_star_path("id" => sentmail.id), data: {  }, class: "btn btn-default btn-xs" do%>
          <i class="glyphicon glyphicon-star"></i>
       <% end %>
       </i>
       <% else %>
        <i class="active clickable">
            <%=link_to sentmails_star_path("id" => sentmail.id), data: {  }, class: "btn btn-default btn-xs" do%>
         <i class="glyphicon glyphicon-star-empty"></i>
       <% end %>
       </i>
       <% end %>
       </td>

        <td style="overflow: hidden;" data-link="<%= sentmails_show_path("id" => sentmail.id) %>" >To:<%= sentmail.to %></td>
        <td style="overflow: hidden;" data-link="<%= sentmails_show_path("id" => sentmail.id) %>">
            <strong><%= sentmail.sub  %></strong>&nbsp;<%= sentmail.body_text %>
        </td>

      <%if sentmail.created_at > Date.today %> 
       <td style="overflow: hidden;" data-link="<%= sentmails_show_path("id" => sentmail.id) %>"><%= sentmail.created_at.in_time_zone.strftime("%I: %m %p")%></td>
       <%else%>
       <td style="overflow: hidden;" data-link="<%= sentmails_show_path("id" => sentmail.id) %>"><%= sentmail.created_at.in_time_zone.strftime("%e %b,%Y")%></td>
       <%end%>
     
     </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<style>

.glyphicon-star {
    color: #FFF000;

}
</style>

<script type="text/javascript">

// $(document).ready(function() {
//   //alert(gon.star_check);
//   if (gon.star_check == 2)
//   { 
//    ('.glyphicon-star').css("color", "#FFF000");  
//   }
//  });



// jQuery(document).ready(function($){
//     $('.clickable').on("click", function(){
       
//         $(this).find('.glyphicon-star').css("color", "#FFF000");
//         // $(this).find('.glyphicon-star').attr("style",'color:#FFF000 !important;');
        

//     });
// });
// $(document).ready(function() {

// $('#selectall').click(function() {
//     $('input[name=sentmail]').prop('checked', true);
// });

// $('#selectall').click(function() {
//     $('input[name=sentmail').prop('checked', false);
// });
// });

$(document).ready(function() {
    $('#sentmailTable').dataTable( {
        initComplete : function() {
         $("#sentmailTable_filter").detach().appendTo('#new-search-area');
           },  
         "columnDefs": [
                        { "width": "5px", "targets": 0 },
                        { "width": "5px", "targets": 1 },
                        { "width": "150px", "targets": 2 },
                        { "width": "400px", "targets": 3 },
                        { "width": "50px", "targets": 4 },
                       
                ],
             
            "dom": '<"top"i>rt<"bottom"flp><"clear">',
           //  order: [[ 4, 'desc' ]]
           select: {
            style:    'os',
            selector: 'td:first-child'
        },
         "bSort" : false
       // order: [[ 4, 'desc' ]]
         } );
} );

// $(document).on('page:load', function(){
//   $(".starry").change(function(){

//       alert("hi......");
//     // var ptstatus=$('.star').attr('data-pt');
//     // $.getScript('/sentmails/star.js?pt=' + ptstatus)
//   });
// });

  
// $(".show").click(function(id){
//   alert("hi......");
//    var data=id;
//    alert(data);
//    console.log(data);
//    $.getScript('/sentmails/show.js?pt='+ JSON.stringify(id));
//   });





$(".delete_link").hide();
$(".starry").click(function() {

  //var captured_id=$(this).prop('value');    

      
    if($('.starry').is(":checked")) {
        $(".delete_link").show();

    } else {
        $(".delete_link").hide();
    }
});


$(".delete_link").click(function() {

var id_list = [];
$.each($("input[name='sentmail[]']:checked"), function(){            
  id_list.push($(this).val());

});
var x=confirm("Are you sure you want to delete?");
if (x)
       $.getScript('/sentmails/destroy_mail.js?pt='+ id_list);
     
  else
return false;
location.reload();
});

jQuery(function($) {
  //alert("hi....");
    $("td[data-link]").click(function() {
      
        window.location = $(this).data('link');    
    });
}); 





</script>

app/views/sentmails/show.html.erb
<div style="position:relative;left:250px;top:-250px;width:1000px;background-color:##ECF0F1;	">
<div >
<p>
  <strong><%= @sentmails.sub %>	</strong>
  
</p>
<hr>
<p>
  <strong>To:</strong>
  <%= @sentmails.to %>
</p>

<hr>
<p>
  <%=raw @sentmails.body %>
</p>
</div>
<p>
  
<hr>
 <div id="sentmails_reply" style="background-color:#ECF0F1;position:absolute;width:1000px;">
    <p>
      click here to 
      <a href="javascript:void(0)" id="reply">Reply</a>or
      <a href="javascript:void(0)" id="forward">Forward</a>
    </p>
  </div>
<hr>
<script >
$("#reply").click(function(){
$("#sentmails_reply").html("<%= escape_javascript(render 'reply') %>");

$("#contacts_field").val(gon.to);
});

$("#forward").click(function(){
$("#sentmails_reply").html("<%= escape_javascript(render 'reply') %>");
$("#body").val(gon.body_text);
});

</script>
</script>

app/views/sentmails/starred.html.erb
<div class="container" id="new-search-area" ></div>
<div class="container" style="position:relative;left:110px;top:-400px;background-color:#ECF0F1; ">

  <table id="sentmailTable" class="display nowrap" cellspacing="0" style="cursor:pointer;table-layout: fixed;">
  <thead>    
  <tr>
      
      <th><div><button class="delete_link">
      <i class="glyphicon glyphicon-trash"></i></button></div>
      </th> 
      <th></th>
      <th></th>
      <th></th>
      <th></th>
  </tr>
  </thead>  

<tbody>
<% @mails.each do |mail| %>
       <!-- <tr data-link="<%= sentmails_show_path("id" => mail.id) %>" > -->
<tr>
    
    <td id ="delete"><%= check_box_tag 'mail[]' , mail.id, false, class: 'starry' %></td> 
<!--  -->      
    <td>

    <% if mail.star_check==2 &&  mail.star_check==2  %>
      <i class="active clickable">
       <%=link_to sentmails_star_path("id" => mail.id), data: {  }, class: "btn btn-default btn-xs" do%>
          <i class="glyphicon glyphicon-star"></i>
       <% end %>
      </i>
    <% else %>

        <i class="active clickable">
         <%=link_to sentmails_star_path("id" => mail.id), data: {  }, class: "btn btn-default btn-xs" do%>
          <i class="glyphicon glyphicon-star-empty"></i>
       <% end %>
       </i>
    <% end %>
       </td>
<!--  -->

        <%if mail.methods.include? :from %> 
         <td style="overflow: hidden;">From:<%= mail.from %></td>
         <%else%>
         <td style="overflow: hidden;">to:<%= mail.to %></td>
         <%end%>
<!--  -->

        <%if mail.methods.include? :from %> 
           <td style="overflow: hidden;">
              <strong><%= mail.sub  %></strong>&nbsp;<%=  mail.parsed_plain_body %></td>
                <%else%>
             <td> <strong><%= mail.sub  %></strong>&nbsp;<%=  mail.body_text %>
            </td>
         <%end%>
 
<!--  -->
       <%if mail.methods.include? :from %>  
           <%if mail.created_at > Date.today %> 
           <td style="overflow: hidden;"><%= mail.date.in_time_zone.strftime("%I: %m %p") %></td>
           <%else%>
           <td style="overflow: hidden;"><%= mail.created_at.strftime("%e %b, %Y")%></td>
           <%end%>
      <%else%>
            <%if mail.created_at > Date.today %> 
           <td style="overflow: hidden;"><%= mail.created_at.in_time_zone.strftime("%I: %m %p") %></td>
           <%else%>
           <td style="overflow: hidden;"><%= mail.created_at.strftime("%e %b, %Y")%></td>
           <%end%>

       <%end%>
</tr>
<% end %>
</tbody>
</table>
</div>
<br>

<style>

.glyphicon-star {
    color: #FFF000;
}
</style>




<script type="text/javascript">
$(document).ready(function() {
    $('#sentmailTable').dataTable( {
        initComplete : function() {
         $("#sentmailTable_filter").detach().appendTo('#new-search-area');
           },  
         "columnDefs": [
                        { "width": "5px", "targets": 0 },
                        { "width": "5px", "targets": 1 },
                        { "width": "150px", "targets": 2 },
                        { "width": "400px", "targets": 3 },
                        { "width": "100px", "targets": 4 },
                       
                ],
           "bSort" : false
         } );
} );

$(".show").click(function(id){
  alert("hi......");
   var data=id;
   alert(data);
   console.log(data);
   $.getScript('/sentmails/show.js?pt='+ JSON.stringify(id));
  });

$(".delete_link").hide();
$(".starry").click(function() {
    if($(this).is(":checked")) {
        $(".delete_link").show();
    } else {
        $(".delete_link").hide();
    }
});

</script>